---
- hosts: all
  become: yes

  pre_tasks:
    - name: Create xml file for testing purpose
      copy:
        src: test.xml
        dest: /tmp/test.xml
        owner: root
        group: root
        mode: 0644

  roles:
    - role: sphinx
