---
- name: Update defaults option for sphinx
  template:
    src: sphinxsearch.default.j2
    dest: /etc/default/sphinxsearch
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Create flat configuration file
  template:
    src: sphinx.conf.j2
    dest: '/etc/sphinxsearch/sphinx.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - rotate all indexes
    - restart sphinx
